version: '3'

services:
  server:
    container_name: video-convert-server-container
    image: video-convert-server
    environment:
      - DATABASE_URL=sqlite://data.db
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
  client:
    container_name: video-convert-client-container
    image: video-convert-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    restart: always
    